### PR TITLE
use elm-mode to support indentation

### PR DESCRIPTION
**Pull request by tsloughter**
Still need to know what to do about the license. elm-mode is gpl3 and the current alpaca-mode is apache2. No idea what, if anything, needs to be done to merge the two.

I also still haven't actually gone through the indentation code to remove what isn't needed from elm.

### CODE REVIEW

**Comment by yurrriq** [comment]
Relevant: http://www.apache.org/licenses/GPL-compatibility.html

**Comment by tsloughter** [comment]
Hm, damn, according to this they are incompatible the way we are doing it :(.

**Comment by tsloughter** [comment]
I changed the license to gpl. I'm happy with gpl and would think the fact that it is an emacs mode would mean it isn't a big deal.

**Comment by yurrriq** [comment]
I'm cool with this. Does anyone else have any opinions?

**Pull request merged**
